# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d30d73c60409175be07781a61e14293dec402d3320f9cb9eb4aca53a734e1bf99fbf836873a23bb039b27e5667f7845fca81b2a8ceba713dbb43194963a8537d

test:
  secret_key_base: fa842c58378653636c06f2e58b72fd4ac2b76c6a4bc9923df3d9e46b1c6b0eea4b7b8522c32bfc2778e7898380fb81e9ceb06e44c427ec7e6aafcfa0e80cc615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
